/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AutomationRouteImport } from './routes/automation'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ElitePackageRouteImport } from './routes/elite-package'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as PricingEstimatesRouteImport } from './routes/pricing-estimates'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PropertyCareRouteImport } from './routes/property-care'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as TermsRouteImport } from './routes/terms'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationRoute = AutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ElitePackageRoute = ElitePackageRouteImport.update({
  id: '/elite-package',
  path: '/elite-package',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingEstimatesRoute = PricingEstimatesRouteImport.update({
  id: '/pricing-estimates',
  path: '/pricing-estimates',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertyCareRoute = PropertyCareRouteImport.update({
  id: '/property-care',
  path: '/property-care',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/automation': typeof AutomationRoute
  '/contact': typeof ContactRoute
  '/elite-package': typeof ElitePackageRoute
  '/platform': typeof PlatformRoute
  '/pricing-estimates': typeof PricingEstimatesRoute
  '/privacy': typeof PrivacyRoute
  '/property-care': typeof PropertyCareRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/automation': typeof AutomationRoute
  '/contact': typeof ContactRoute
  '/elite-package': typeof ElitePackageRoute
  '/platform': typeof PlatformRoute
  '/pricing-estimates': typeof PricingEstimatesRoute
  '/privacy': typeof PrivacyRoute
  '/property-care': typeof PropertyCareRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/automation': typeof AutomationRoute
  '/contact': typeof ContactRoute
  '/elite-package': typeof ElitePackageRoute
  '/platform': typeof PlatformRoute
  '/pricing-estimates': typeof PricingEstimatesRoute
  '/privacy': typeof PrivacyRoute
  '/property-care': typeof PropertyCareRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/automation'
    | '/contact'
    | '/elite-package'
    | '/platform'
    | '/pricing-estimates'
    | '/privacy'
    | '/property-care'
    | '/services'
    | '/terms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/automation'
    | '/contact'
    | '/elite-package'
    | '/platform'
    | '/pricing-estimates'
    | '/privacy'
    | '/property-care'
    | '/services'
    | '/terms'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/automation'
    | '/contact'
    | '/elite-package'
    | '/platform'
    | '/pricing-estimates'
    | '/privacy'
    | '/property-care'
    | '/services'
    | '/terms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AutomationRoute: typeof AutomationRoute
  ContactRoute: typeof ContactRoute
  ElitePackageRoute: typeof ElitePackageRoute
  PlatformRoute: typeof PlatformRoute
  PricingEstimatesRoute: typeof PricingEstimatesRoute
  PrivacyRoute: typeof PrivacyRoute
  PropertyCareRoute: typeof PropertyCareRoute
  ServicesRoute: typeof ServicesRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automation': {
      id: '/automation'
      path: '/automation'
      fullPath: '/automation'
      preLoaderRoute: typeof AutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elite-package': {
      id: '/elite-package'
      path: '/elite-package'
      fullPath: '/elite-package'
      preLoaderRoute: typeof ElitePackageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing-estimates': {
      id: '/pricing-estimates'
      path: '/pricing-estimates'
      fullPath: '/pricing-estimates'
      preLoaderRoute: typeof PricingEstimatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property-care': {
      id: '/property-care'
      path: '/property-care'
      fullPath: '/property-care'
      preLoaderRoute: typeof PropertyCareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AutomationRoute: AutomationRoute,
  ContactRoute: ContactRoute,
  ElitePackageRoute: ElitePackageRoute,
  PlatformRoute: PlatformRoute,
  PricingEstimatesRoute: PricingEstimatesRoute,
  PrivacyRoute: PrivacyRoute,
  PropertyCareRoute: PropertyCareRoute,
  ServicesRoute: ServicesRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
